server:
  port: 9011
database:
  url: mariadb://localhost:3306/middle_data
  username: root
  password: 369
redis:
  url: 43.134.32.208:6379
  username:
  password: jhkdjhkjdhsIUTYURTU_sCDs5d
  expire: 7200